src/main/java/com/core/foreign/api/contract/controller/ContractController.java, src/main/java/com/core/foreign/api/contract/dto/ContractPreviewResponseDTO.java, src/main/java/com/core/foreign/api/contract/dto/EmployeeCompletedContractResponseDTO.java, src/main/java/com/core/foreign/api/contract/dto/EmployerCompletedContractResponseDTO.java, src/main/java/com/core/foreign/api/contract/entity/ContractMetadata.java, src/main/java/com/core/foreign/api/contract/repository/ContractMetadataRepository.java, src/main/java/com/core/foreign/api/contract/service/ContractCreator.java, src/main/java/com/core/foreign/api/contract/service/ContractService.java, src/main/java/com/core/foreign/api/contract/service/ContractUpdater.java, src/main/java/com/core/foreign/api/member/controller/MemberController.java, src/main/java/com/core/foreign/api/recruit/dto/RecruitPreviewInContractResponseDTO.java, src/main/java/com/core/foreign/api/recruit/entity/Resume.java, src/main/java/com/core/foreign/api/recruit/service/RecruitService.java, src/main/java/com/core/foreign/api/recruit/service/ResumeService.java, src/main/java/com/core/foreign/common/response/ErrorStatus.java, src/main/java/com/core/foreign/common/response/SuccessStatus.java
- close #89 
- 피고용인과 고용인은 완료된 계약서를 조회할 수 있습니다.
- 계약서 기능이 완료되어 개발 전 임시로 작성해두었던 로직을 수정합니다.
=> [FEAT] 마이페이지 근로 계약서 조회.

src/main/java/com/core/foreign/api/contract/controller/ContractController.java, src/main/java/com/core/foreign/api/contract/dto/ContractPreviewResponseDTO.java, src/main/java/com/core/foreign/api/contract/service/ContractService.java, src/main/java/com/core/foreign/api/file/FileDirAndName.java, src/main/java/com/core/foreign/api/file/controller/FileController.java, src/main/java/com/core/foreign/api/member/repository/EmployeePortfolioRepository.java, src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java, src/main/java/com/core/foreign/api/member/service/MemberService.java, src/main/java/com/core/foreign/api/portfolio/dto/ApplicationPortfolioResponseDTO.java, src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java, src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumePreviewResponseDTO.java, src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumeResponseDTO.java, src/main/java/com/core/foreign/api/recruit/dto/MyDraftRecruitResponseDTO.java, src/main/java/com/core/foreign/api/recruit/dto/MyRecruitResponseDTO.java, src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioRequestDTO.java, src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioTextResponseDTO.java, src/main/java/com/core/foreign/api/recruit/repository/RecruitRepository.java, src/main/java/com/core/foreign/api/recruit/service/RecruitService.java, src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java, src/main/java/com/core/foreign/api/recruit/service/ResumeService.java, src/main/java/com/core/foreign/common/response/ErrorStatus.java
- close #95 
- 공고 지원 관련 예외 추가
- 공고 지원 시 사진 업로드 추가
- 계약서 업로드 시 url 리턴
- 필요 없는 부분 삭제 및 오타 수정
=> [FIX] 예외 처리 테스트

src/main/java/com/core/foreign/api/contract/controller/ContractController.java, src/main/java/com/core/foreign/api/contract/dto/EmployeeCompletedContractResponseDTO.java, src/main/java/com/core/foreign/api/contract/entity/Contract.java, src/main/java/com/core/foreign/api/contract/entity/ContractMetadata.java, src/main/java/com/core/foreign/api/contract/entity/FileUploadContract.java, src/main/java/com/core/foreign/api/contract/repository/ContractMetadataRepository.java, src/main/java/com/core/foreign/api/contract/service/ContractService.java, src/main/java/com/core/foreign/api/contract/service/ContractUpdater.java, src/main/java/com/core/foreign/api/contract/service/ContractUtils.java, src/main/java/com/core/foreign/common/response/ErrorStatus.java
- close #98 
- 파일 계약서 업로드 시 피고용인과 고용인 중 한 명만 업로드 해도 인정.
- 계약서 수정 api 추가.
=> [FIX] 계약서 부분 수정.

src/main/java/com/core/foreign/common/config/swagger/SwaggerConfig.java
- close #100 
- 불 필요한 스웨거 문구를 수정하였습니다.
=> [FIX] 스웨거 문구 수정

src/main/java/com/core/foreign/api/contract/controller/ContractController.java, src/main/java/com/core/foreign/api/contract/service/ContractService.java, src/main/java/com/core/foreign/api/member/controller/MemberController.java, src/main/java/com/core/foreign/api/payment/controller/PaymentController.java, src/main/java/com/core/foreign/api/payment/service/PaymentService.java, src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java, src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java, src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java, src/main/java/com/core/foreign/api/recruit/service/RecruitService.java, src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java, src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
- close #104 
- 현재 페이징 처리는 무한 스크롤이 아니므로 무한 스크롤 관련 부분 제거
=> [FIX] 페이지 응답 불필요한 부분 제거.

src/main/java/com/core/foreign/api/contract/controller/ContractController.java, src/main/java/com/core/foreign/api/contract/dto/AdminContractPreviewResponseDTO.java, src/main/java/com/core/foreign/api/contract/entity/ContractMetadata.java, src/main/java/com/core/foreign/api/contract/entity/FileUploadContract.java, src/main/java/com/core/foreign/api/contract/repository/ContractMetadataRepository.java, src/main/java/com/core/foreign/api/contract/service/ContractReader.java, src/main/java/com/core/foreign/api/contract/service/ContractService.java, src/main/java/com/core/foreign/api/contract/service/ContractUpdater.java, src/main/java/com/core/foreign/api/contract/service/ContractUtils.java, src/main/java/com/core/foreign/api/member/controller/MemberController.java, src/main/java/com/core/foreign/api/member/dto/EmployerCompanyInfoResponseDTO.java, src/main/java/com/core/foreign/api/member/entity/Employer.java, src/main/java/com/core/foreign/api/member/entity/EmployerEmployee.java, src/main/java/com/core/foreign/api/member/entity/EmployerResume.java, src/main/java/com/core/foreign/api/member/repository/EmployeeRepository.java, src/main/java/com/core/foreign/api/member/repository/EmployerEmployeeRepository.java, src/main/java/com/core/foreign/api/member/repository/EmployerResumeRepository.java, src/main/java/com/core/foreign/api/member/repository/MemberRepository.java, src/main/java/com/core/foreign/api/member/service/EvaluationService.java, src/main/java/com/core/foreign/api/member/service/MemberService.java, src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java, src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java, src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java, src/main/java/com/core/foreign/api/recruit/entity/Resume.java, src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java, src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java, src/main/java/com/core/foreign/api/recruit/service/ResumeService.java, src/main/java/com/core/foreign/common/response/ErrorStatus.java
- close #108 
- 평가 시 모집 승인 시간이 아닌 계약서 완료 시간으로 변경되어  계약서 수정 시간 기록.
- 관리자가 파일 업로드를 확인하고 승인/반려 시 파일이 변경되었을 경우 예외 처리.
- 기본 포트폴리오와 실제 지원 포트폴리오 찜하기 구분
=> [FIX] 계약서와 찜하기 부분 수정.

src/main/java/com/core/foreign/api/contract/controller/ContractController.java, src/main/java/com/core/foreign/api/contract/service/ContractReader.java, src/main/java/com/core/foreign/api/contract/service/ContractService.java, src/main/java/com/core/foreign/api/member/controller/MemberController.java, src/main/java/com/core/foreign/api/payment/controller/PaymentController.java, src/main/java/com/core/foreign/api/payment/service/PaymentService.java, src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java, src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java, src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java, src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java, src/main/java/com/core/foreign/api/recruit/service/RecruitService.java, src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java, src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
- close #111 
- 고용인 지원 현황 조회 시 size 추가 및 쿼리 대소문자 구분.
=> [FIX] 고용인 지원 현황 조회 시 size 추가 및 쿼리 대소문자 구분.

src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java, src/main/java/com/core/foreign/common/advice/ControllerExceptionAdvice.java, src/main/java/com/core/foreign/common/slack/SlackNotificationService.java
- close #114
- 슬랙 웹훅 임시 중지하였습니다.
=> [REFAC] 슬랙 웹훅 임시 중지

src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
- close #116 
- queryDSL 동적 쿼리 작성 시 null 처리 로직을 추가했습니다.
=> [FIX] queryDSL null 처리 추가.

src/main/java/com/core/foreign/api/contract/dto/EmployerCompletedContractResponseDTO.java
- close #118 
고용인 완료된 계약서 조회 디자인 화면으로 수정.
=> [FIX] 고용인 완료된 계약서 조회 디자인 화면으로 수정.

src/main/java/com/core/foreign/api/contract/dto/EmployeeCompletedContractResponseDTO.java, src/main/java/com/core/foreign/api/contract/dto/EmployerCompletedContractResponseDTO.java, src/main/java/com/core/foreign/api/contract/service/ContractReader.java, src/main/java/com/core/foreign/api/contract/service/ContractService.java, src/main/java/com/core/foreign/api/member/controller/MemberController.java
- close #120 
- 완료된 계약서 상세 조회.
- 완료된 계약서 리스트 조회 시 계약서 타입 추가.
=> [FEAT] 완료된 계약서 상세 조회.

src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java, src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java, src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java, src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryQueryDSL.java
- close #123 
- 포트폴리오 실제 지원 필터링 구현.
=> [FEAT] 포트폴리오 실제 지원 필터링 구현.

src/main/java/com/core/foreign/api/member/entity/Employee.java, src/main/java/com/core/foreign/api/member/repository/EmployeeRepository.java, src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java, src/main/java/com/core/foreign/api/portfolio/dto/ApplicationPortfolioResponseDTO.java, src/main/java/com/core/foreign/api/portfolio/dto/BasicPortfolioResponseDTO.java, src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java, src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioRequestDTO.java, src/main/java/com/core/foreign/api/recruit/entity/Resume.java, src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java, src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
- close #125 
기본 및 실제 지원 포트폴리오 조회수 추가.
=> [FIX] 포트폴리오 조회수 추가

src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
- close #128 
- 공고 지원 시 승인 날짜를  MySQL에서 허용하는 최대 날짜로 설정
=> [FIX] 공고 지원 시 모집 승인 날짜 수정.

src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java, src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
- close #130 
- 실제 지원 포트폴리오 조회 시 필터 수정.
=> [FIX] 실제 지원 포트폴리오 조회 시 필터 수정.

build.gradle
=> [FIX] 쿼리 출력 의존성 추가.

src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
- close #134 
- 쿼리 실행 전 로그 추가.
=> [FIX] 쿼리 실행 전 로그 추가.

src/main/java/com/core/foreign/api/recruit/service/RecruitSpecifications.java
- close #136
- distinct를 활용하여 중복 데이터가 반환되지 않도록 수정하였습니다.
=> [FIX] 동적 검색 뻥튀기 문제 해결

src/main/java/com/core/foreign/api/member/repository/EmployerEmployeeRepository.java, src/main/java/com/core/foreign/api/member/repository/EmployerResumeRepository.java, src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java, src/main/java/com/core/foreign/api/portfolio/dto/ApplicationPortfolioResponseDTO.java, src/main/java/com/core/foreign/api/portfolio/dto/BasicPortfolioResponseDTO.java, src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java
- close #138 
포트폴리오 조회 시 찜 유무 추가.
=> [FIX] 포트폴리오 조회 시 찜 유무 추가.

src/main/java/com/core/foreign/api/member/entity/Employer.java, src/main/java/com/core/foreign/api/member/service/MemberService.java
- close #140 
-가입 시 회사 주소 추가.
-회사 주소 업데이트 수정.
=> [FIX] 고용인 가입 시 개인 주소랑 회사 주소 같음.

src/main/java/com/core/foreign/api/recruit/service/RecruitSpecifications.java
- close #144
- 기존 동적 필터링에서 불 필요한 조인을 제거하여 로직을 간소화 하였습니다.
=> [FIX] 동적 필터링 로직 간소화

src/main/java/com/core/foreign/common/config/security/SecurityConfig.java
=> [REFAC] 프론트 cors 허용

src/main/java/com/core/foreign/api/member/dto/MemberLoginResponseDTO.java, src/main/java/com/core/foreign/api/member/service/MemberService.java
- close #154 
- 로그인 성공 시 회원의 이름이랑 id 반환.
=> [FIX] 로그인 시 회원 이름과 id 반환.

src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java, src/main/java/com/core/foreign/api/recruit/dto/RecruitDetailResponseDTO.java, src/main/java/com/core/foreign/api/recruit/dto/RecruitRequestDTO.java, src/main/java/com/core/foreign/api/recruit/dto/RecruitResponseDTO.java, src/main/java/com/core/foreign/api/recruit/entity/GeneralRecruit.java, src/main/java/com/core/foreign/api/recruit/entity/PremiumRecruit.java, src/main/java/com/core/foreign/api/recruit/entity/Recruit.java, src/main/java/com/core/foreign/api/recruit/repository/RecruitBookmarkRepository.java, src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
- close #160 
- 공고 상세 조회 시 모집 인원 및 찜하기 상태 추가.
=> [FIX] 공고 상세 조회 시 모집 인원 및 찜하기 상태 추가.

src/main/java/com/core/foreign/api/recruit/dto/RecruitPreviewResponseDTO.java, src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
- close #164 
공고 미리보기 추가된 데이터 추가.
=> [FIX] 공고 미리보기 추가된 데이터 추가.

src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java, src/main/java/com/core/foreign/api/recruit/repository/ResumeRepositoryImpl.java
- close #166 
- 프리미엄 공고 이력서만 포트폴리오에 표시
- 프리미엄 공고 없음
- 프리미엄 공고 있음
=> [FIX] 프리미엄 공고 이력서만 포트폴리오에 표시

src/main/java/com/core/foreign/api/member/dto/EmployeePortfolioDTO.java, src/main/java/com/core/foreign/api/member/entity/EmployeePortfolio.java, src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java, src/main/java/com/core/foreign/api/portfolio/dto/internal/BasicPortfolioDTO.java, src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumeResponseDTO.java, src/main/java/com/core/foreign/api/recruit/dto/MyResumeResponseDTO.java
- close #168 
- 피고용인 englishTestScore, englishTestType 제거
=> [FIX] 피고용인 englishTestScore, englishTestType 제거

src/main/java/com/core/foreign/api/aws/service/S3Service.java, src/main/java/com/core/foreign/api/contract/service/ContractService.java, src/main/java/com/core/foreign/api/file/FileDirAndName.java, src/main/java/com/core/foreign/api/file/controller/FileController.java, src/main/java/com/core/foreign/api/file/service/FileService.java, src/main/java/com/core/foreign/common/response/SuccessStatus.java
- close #171
- 기존 4개의 파일 업로드 엔드포인트를 하나의 엔드포인트로 간소화 하였습니다.
=> [FIX] 파일 업로드 엔드포인트 간소화

src/main/java/com/core/foreign/api/member/controller/MemberController.java, src/main/java/com/core/foreign/api/member/dto/EmployeePortfolioDTO.java, src/main/java/com/core/foreign/api/member/entity/EmployeePortfolio.java, src/main/java/com/core/foreign/api/member/entity/EmployeePortfolioStatus.java, src/main/java/com/core/foreign/api/member/entity/Topik.java, src/main/java/com/core/foreign/api/member/repository/EmployeePortfolioRepository.java, src/main/java/com/core/foreign/api/member/repository/ResumeEvaluationRepository.java, src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java, src/main/java/com/core/foreign/api/member/service/MemberService.java, src/main/java/com/core/foreign/api/portfolio/dto/internal/BasicPortfolioDTO.java, src/main/java/com/core/foreign/api/portfolio/dto/response/BasicPortfolioResponseDTO.java, src/main/java/com/core/foreign/api/portfolio/service/PortfolioReader.java, src/main/java/com/core/foreign/api/recruit/dto/ApplicationResumeResponseDTO.java, src/main/java/com/core/foreign/api/recruit/dto/MyResumeResponseDTO.java, src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
- close #170 
- 피고용인 포트폴리오 임시 저장 부분 삭제
- Topic -> Topik 수정
- 피고용인 포트폴리오 조회 시 없을 때 빈 거 응답.
=> [FIX] 피고용인 포트폴리오 임시 저장 부분 삭제

src/main/java/com/core/foreign/api/member/repository/EmployeePortfolioRepository.java, src/main/java/com/core/foreign/api/member/service/EmployeePortfolioService.java, src/main/java/com/core/foreign/api/member/service/MemberService.java, src/main/java/com/core/foreign/api/recruit/service/ResumeService.java, src/main/java/com/core/foreign/common/response/ErrorStatus.java
- close #174 
- 포트폴리오 조회 시 없을 경우 예외 처리.
=> [FIX] 포트폴리오 조회 시 없을 경우 예외 처리.

src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java, src/main/java/com/core/foreign/api/recruit/dto/PortfolioResponseDTO.java, src/main/java/com/core/foreign/api/recruit/dto/PremiumResumeRequestDTO.java, src/main/java/com/core/foreign/api/recruit/dto/ResumePortfolioRequestDTO.java, src/main/java/com/core/foreign/api/recruit/dto/internal/ResumeDTO.java, src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
- close #176 
- 프리미엄 공고 지원 dto 수정
- 사장님이 등록한 형식 조회 시 portfolio_id 카멜케이스로 수정
=> [FIX] 프리미엄 공고 지원 dto 수정

src/main/java/com/core/foreign/api/contract/service/ContractReader.java, src/main/java/com/core/foreign/api/contract/service/ContractService.java, src/main/java/com/core/foreign/api/contract/service/ContractUpdater.java, src/main/java/com/core/foreign/api/contract/service/ContractUtils.java, src/main/java/com/core/foreign/api/member/controller/MemberController.java, src/main/java/com/core/foreign/api/member/service/EmailService.java, src/main/java/com/core/foreign/api/member/service/EvaluationService.java, src/main/java/com/core/foreign/api/member/service/MemberService.java, src/main/java/com/core/foreign/api/portfolio/service/PortfolioService.java, src/main/java/com/core/foreign/api/recruit/dto/MyDraftRecruitResponseDTO.java, src/main/java/com/core/foreign/api/recruit/dto/MyRecruitResponseDTO.java, src/main/java/com/core/foreign/api/recruit/dto/RecruitmentApplyStatusDTO.java, src/main/java/com/core/foreign/api/recruit/repository/RecruitRepositoryImpl.java, src/main/java/com/core/foreign/api/recruit/service/RecruitService.java, src/main/java/com/core/foreign/api/recruit/service/ResumeReader.java, src/main/java/com/core/foreign/api/recruit/service/ResumeService.java
- close #180 
- 화면 정의서와 디자인 페이지 비교 후 DTO 수정
- 서비스 로직 NOT_FOUND_EXCEPTION 발생 시 BadRequestException 에서 NotFoundException 으로 수정
- 고용인 등록한 공고 리스트 조회 시 주소 추가
- 고용인 지원 현황 조회 시 주소 추가
- 임시 저장한 공고 리스트 조회 시 수정 날짜 제거
=> [FIX] 화면 정의서와 디자인 페이지 비교 후 DTO 수정 및 에러 코드 수정

src/main/java/com/core/foreign/api/contract/controller/ContractController.java, src/main/java/com/core/foreign/api/member/controller/AuthController.java, src/main/java/com/core/foreign/api/member/controller/MemberController.java, src/main/java/com/core/foreign/api/member/dto/AddressDTO.java, src/main/java/com/core/foreign/api/member/dto/AgreementRequestDTO.java, src/main/java/com/core/foreign/api/member/dto/BusinessVerificationRequestDTO.java, src/main/java/com/core/foreign/api/member/dto/EmployerBasicInfoUpdateRequestDTO.java, src/main/java/com/core/foreign/api/member/dto/EvaluationCategoryResponseDTO.java, src/main/java/com/core/foreign/api/member/repository/ResumeEvaluationRepository.java, src/main/java/com/core/foreign/api/member/service/EvaluationDeleter.java, src/main/java/com/core/foreign/api/member/service/EvaluationReader.java, src/main/java/com/core/foreign/api/member/service/EvaluationService.java, src/main/java/com/core/foreign/api/portfolio/controller/PortfolioController.java, src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java, src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java, src/main/java/com/core/foreign/common/response/ErrorStatus.java, src/main/java/com/core/foreign/common/response/SuccessStatus.java
- close #183 
- 스웨거 정보 수정.
- 요청 시 개인 정보 관련 데이터  RequestParm -> RequestBody 로 수정 (ex) 이메일, 번호, 주소)
- 평가 삭제하기 추가.
- 스웨거 수정 예시
-이메일
- 번호
-주소
-평가 삭제
=> [REFAC] 스웨거 정보 수정

src/main/java/com/core/foreign/api/member/controller/MemberController.java, src/main/java/com/core/foreign/api/member/service/EvaluationReader.java, src/main/java/com/core/foreign/api/member/service/EvaluationService.java, src/main/java/com/core/foreign/api/recruit/controller/RecruitController.java, src/main/java/com/core/foreign/api/recruit/dto/RecruitDetailResponseDTO.java, src/main/java/com/core/foreign/api/recruit/entity/Resume.java, src/main/java/com/core/foreign/api/recruit/repository/ResumeRepository.java, src/main/java/com/core/foreign/api/recruit/service/RecruitService.java
- close #185 
- 평가 삭제 시 이력서 반영
- 공고 상세 조회 시 평가 상태 추가
- 공고 상세 조회 시 평가 유무
- 평가 삭제 전
- 평가 삭제 완료
- 평가 삭제 후
=> [FIX] 평가 취소 시 이력서 상태 변경
